name = "webnari-commerce"
main = "worker.js"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "webnari.io/commerce/*", zone_name = "webnari.io" }
]

[vars]
ALLOWED_ORIGINS = "https://webnari.io,https://wookwearshop.com,http://localhost:3000,https://webnari-store-admin.webnari.workers.dev,https://wook-wear.webnari.workers.dev"
